### PR TITLE
Create Lol

### PR DESCRIPTION
**Pull request by Lolgetgone**

### CODE REVIEW

**Comment by brennabre** [comment]
BRUH

**Comment by 2sus2uy** [comment]
what

**Comment by brennabre** [comment]
?????

**Review by 1wwwedd — COMMENTED** [review]
eee

**Comment by KittyMasta** [comment]
can someone make me a hacked prodigy account with all epics, all pets, all armor, level 100 (with full map unlocked) ty!!!
if u could tell me pass and user i would be very happy

**Pull request closed without merging**
